theme: jekyll-theme-minimal
title: Allen McDermott
description: Website under construction | Software Developer | Seeking New Opportunities
remote_theme: pages-themes/minimal@v0.2.0

# These show up in the sidebar of the Minimal theme automatically
github_username: allengmcd
# linkedin_username: your-profile-name 

# Build settings
markdown: kramdown
permalink: /:title/
