theme: jekyll-theme-minimal
title: Allen McDermott's homepage
description: >
  Website under construction | Software Developer | Seeking New Opportunities <br>
  <a href="https://www.linkedin.com/in/allen-mcdermott-2038863b2">View LinkedIn Profile</a>
author: Allen McDermott  
github_username: allengmcd

# Build settings
markdown: kramdown
permalink: /:title/
